# Generated by Django 4.2.3 on 2023-08-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userotp_otp_alter_userotp_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscollectsliver',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adscollectsliver',
            name='watch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(default='9253', max_length=6),
        ),
    ]
