# Generated by Django 4.2.3 on 2023-08-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_adscollectsliver_active_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adscollectsliver',
            name='sl_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(default='9918', max_length=6),
        ),
    ]
