# Generated by Django 4.2.3 on 2023-08-06 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(default='7454', max_length=6),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdsCollectSliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=0, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('active_at', models.DateTimeField()),
                ('is_ready', models.BooleanField(default=False)),
                ('is_watched', models.BooleanField(default=False)),
                ('watch_at', models.DateTimeField()),
                ('ads_information', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_ads_collect_silver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
